# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'KalkulatorBmr.ui'
#
# Created by: PyQt5 UI code generator 5.15.6
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_KalkulatorBmr(object):
    def setupUi(self, KalkulatorBmr):
        KalkulatorBmr.setObjectName("KalkulatorBmr")
        KalkulatorBmr.resize(249, 373)
        self.kalkulator_bmr = QtWidgets.QWidget(KalkulatorBmr)
        self.kalkulator_bmr.setObjectName("kalkulator_bmr")
        self.label = QtWidgets.QLabel(self.kalkulator_bmr)
        self.label.setGeometry(QtCore.QRect(10, 10, 241, 41))
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.label.setFont(font)
        self.label.setAlignment(QtCore.Qt.AlignCenter)
        self.label.setObjectName("label")
        self.label_2 = QtWidgets.QLabel(self.kalkulator_bmr)
        self.label_2.setGeometry(QtCore.QRect(10, 70, 101, 41))
        self.label_2.setObjectName("label_2")
        self.label_3 = QtWidgets.QLabel(self.kalkulator_bmr)
        self.label_3.setGeometry(QtCore.QRect(0, 120, 111, 31))
        self.label_3.setObjectName("label_3")
        self.label_4 = QtWidgets.QLabel(self.kalkulator_bmr)
        self.label_4.setGeometry(QtCore.QRect(0, 160, 111, 41))
        self.label_4.setObjectName("label_4")
        self.label_5 = QtWidgets.QLabel(self.kalkulator_bmr)
        self.label_5.setGeometry(QtCore.QRect(0, 210, 111, 41))
        self.label_5.setObjectName("label_5")
        self.Txt_umur = QtWidgets.QLineEdit(self.kalkulator_bmr)
        self.Txt_umur.setGeometry(QtCore.QRect(120, 80, 113, 20))
        self.Txt_umur.setObjectName("Txt_umur")
        self.cmb_kelamin = QtWidgets.QComboBox(self.kalkulator_bmr)
        self.cmb_kelamin.setGeometry(QtCore.QRect(120, 120, 69, 22))
        self.cmb_kelamin.setObjectName("cmb_kelamin")
        self.cmb_kelamin.addItem("")
        self.cmb_kelamin.addItem("")
        self.Txt_tb = QtWidgets.QLineEdit(self.kalkulator_bmr)
        self.Txt_tb.setGeometry(QtCore.QRect(120, 170, 113, 20))
        self.Txt_tb.setObjectName("Txt_tb")
        self.Txt_bb = QtWidgets.QLineEdit(self.kalkulator_bmr)
        self.Txt_bb.setGeometry(QtCore.QRect(120, 220, 113, 20))
        self.Txt_bb.setObjectName("Txt_bb")
        self.PB_hitung = QtWidgets.QPushButton(self.kalkulator_bmr)
        self.PB_hitung.setGeometry(QtCore.QRect(90, 260, 75, 23))
        self.PB_hitung.setObjectName("PB_hitung")
        self.label_hasil = QtWidgets.QLabel(self.kalkulator_bmr)
        self.label_hasil.setGeometry(QtCore.QRect(70, 290, 171, 81))
        self.label_hasil.setText("")
        self.label_hasil.setObjectName("label_hasil")
        self.label_7 = QtWidgets.QLabel(self.kalkulator_bmr)
        self.label_7.setGeometry(QtCore.QRect(0, 290, 71, 71))
        self.label_7.setObjectName("label_7")
        KalkulatorBmr.setCentralWidget(self.kalkulator_bmr)

        self.retranslateUi(KalkulatorBmr)
        QtCore.QMetaObject.connectSlotsByName(KalkulatorBmr)

    def retranslateUi(self, KalkulatorBmr):
        _translate = QtCore.QCoreApplication.translate
        KalkulatorBmr.setWindowTitle(_translate("KalkulatorBmr", "Kalkulator Bmr"))
        self.label.setText(_translate("KalkulatorBmr", "KALKULATOR BMR"))
        self.label_2.setText(_translate("KalkulatorBmr", "<html><head/><body><p><span style=\" font-size:10pt;\">Umur</span></p></body></html>"))
        self.label_3.setText(_translate("KalkulatorBmr", "<html><head/><body><p><span style=\" font-size:10pt;\">Kelamin</span></p></body></html>"))
        self.label_4.setText(_translate("KalkulatorBmr", "<html><head/><body><p><span style=\" font-size:10pt;\">Tinggi Badan(Cm)</span></p></body></html>"))
        self.label_5.setText(_translate("KalkulatorBmr", "<html><head/><body><p><span style=\" font-size:10pt;\">Berat Badan(Kg)</span></p></body></html>"))
        self.cmb_kelamin.setItemText(0, _translate("KalkulatorBmr", "PRIA"))
        self.cmb_kelamin.setItemText(1, _translate("KalkulatorBmr", "WANITA"))
        self.PB_hitung.setText(_translate("KalkulatorBmr", "HITUNG"))
        self.label_7.setText(_translate("KalkulatorBmr", "BMR  ANDA :"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    KalkulatorBmr = QtWidgets.QMainWindow()
    ui = Ui_KalkulatorBmr()
    ui.setupUi(KalkulatorBmr)
    KalkulatorBmr.show()
    sys.exit(app.exec_())
