# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'MainForm.ui'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets
from KalkulatorBmr import *
from KalkulatorBmr_prog import *
from KalkulatorBMI import*
from KalkulatorBMI_prog import*

class Ui_Form(object):

    def bmr(self):
        self.BMR = QtWidgets.QMainWindow()
        self.ui = Ui_KalkulatorBmr()
        self.ui.setupUi(self.BMR)
        self.ui.signals()
        self.BMR.show()
    
    def bmi(self):
        self.BMI = QtWidgets.QMainWindow()
        self.uis = Ui_MainWindow()
        self.uis.setupUi(self.BMI)
        self.uis.signals()
        self.BMI.show()

    def setupUi(self, Form):
        Form.setObjectName("Form")
        Form.resize(231, 290)
        self.label = QtWidgets.QLabel(Form)
        self.label.setGeometry(QtCore.QRect(60, 50, 121, 16))
        font = QtGui.QFont()
        font.setPointSize(9)
        font.setBold(True)
        font.setWeight(75)
        self.label.setFont(font)
        self.label.setObjectName("label")
        self.push_bmr = QtWidgets.QPushButton(Form)
        self.push_bmr.setGeometry(QtCore.QRect(60, 110, 121, 41))
        font = QtGui.QFont()
        font.setPointSize(8)
        self.push_bmr.setFont(font)
        self.push_bmr.setObjectName("push_bmr")
        self.push_bmr.clicked.connect(self.bmr)

        self.push_bmi = QtWidgets.QPushButton(Form)
        self.push_bmi.setGeometry(QtCore.QRect(60, 170, 121, 41))
        font = QtGui.QFont()
        font.setPointSize(8)
        self.push_bmi.setFont(font)
        self.push_bmi.setObjectName("push_bmi")
        self.push_bmi.clicked.connect(self.bmi)


        self.retranslateUi(Form)
        QtCore.QMetaObject.connectSlotsByName(Form)

    def retranslateUi(self, Form):
        _translate = QtCore.QCoreApplication.translate
        Form.setWindowTitle(_translate("Form", "Form"))
        self.label.setText(_translate("Form", "Pilih Kalkulator"))
        self.push_bmr.setText(_translate("Form", "Kalkulator BMR"))
        self.push_bmi.setText(_translate("Form", "Kalkulator BMI"))

if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    FormMainWindow = QtWidgets.QMainWindow()
    ui = Ui_Form()
    ui.setupUi(FormMainWindow)
    FormMainWindow.show()
    sys.exit(app.exec_())

